### ISSUE TITLE
Parser doesn't fail gracefully on invalid command line inputs

### ISSUE THREAD

**Issue by balasub** [VUISIS/formula#36]
Screenshot of model, inputs, and call stack below demonstrate the bug. The upstream code should be reworked so that this fails gracefully before resulting in a null reference in the visitor.

![image](https://user-images.githubusercontent.com/4978678/232816910-b995c24c-ebdc-4f34-9e1c-93ed52211979.png)

**Comment by saj122** [comment]
Issues is caused by launching from Visual Studio on Windows with the debugger attached.
